apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 66.3.0
    chart: kube-prometheus-stack
    helm:
      releaseName: prometheus-stack
      values: |
        grafana:
          service:
            type: ClusterIP # LoadBalancer yerine ClusterIP yapıldı
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - grafana.52.57.83.49.nip.io
            path: /
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true