apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: v1.0.69 
    chart: reloader
  destination:
    server: https://kubernetes.default.svc
    namespace: default #reloader'ın kurulacağı yer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true