apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sock-shop
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/emircarikci-kloia/sock-shop-case.git
    targetRevision: HEAD
    path: helm-chart 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sock-shop
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true