apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.28.0
    helm:
      values: |
        server:
          dev:
            enabled: true
          extraEnvironmentVars:
            VAULT_ADDR: "http://127.0.0.1:8200"
            VAULT_API_ADDR: "http://0.0.0.0:8200"
        ui:
          enabled: true
          serviceType: "ClusterIP" 
          serviceNodePort: null
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - host: vault.52.57.83.49.nip.io
            pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true