apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.28.0 
    helm:
      values: |
        server:
          dev:
            enabled: true
        ui:
          enabled: true
          serviceType: "LoadBalancer"
          serviceNodePort: null
          service:
            port: 80
            targetPort: 8200
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true