apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: sock-shop 
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200" 
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "sock-shop-role" 
          serviceAccountRef:
            name: default
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secret-from-vault
  namespace: sock-shop
spec:
  refreshInterval: "15s" # 15 saniyede bir kontrol
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: sock-shop-db-secret 
    creationPolicy: Owner
  data:
  - secretKey: password 
    remoteRef:
      key: secret/sock-shop/database 
      property: password 